module = "icon"

[glyphs]
refresh = "fontawesome-arrows-cw"
tick = "fontawesome-ok"
trash = "fontawesome-trash-empty"
right_arrow = "typicons-right"
left_arrow = "typicons-left"
github = "brandico-github-text"
lock = "typicons-lock"
pin = "typicons-pin-outline"
